version: '3.7'
services:

  app-redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - redis-bank-network
    restart: always

  app-redisbank:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=app-redis
      - REDIS_PORT=6379
      - GITPOD_WORKSPACE_ID=${GITPOD_WORKSPACE_ID:-}
      - GITPOD_WORKSPACE_CLUSTER_HOST=${GITPOD_WORKSPACE_CLUSTER_HOST:-}
      - SPRING_PROFILES_ACTIVE=${GITPOD:-}
    ports:
      - "8080:8080"
    networks:
      - redis-bank-network
    restart: always
    depends_on:
      - app-redis

networks:
  redis-bank-network:
    driver: bridge
